resourcePackages:
- fr.zenika.prezopenapi.resources
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0'
    title: Zenika prez example
    description: 'Hello world !'
    termsOfService: https://zenika.com
    contact:
      email: jobs@zenika.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html